---
- name: Install ArgoCD on Kubernetes
  hosts: webservers
  become: no
  tasks:
    - name: Install ArgoCD using kubectl
      shell: |
        kubectl create namespace argocd
        kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      register: argo_install
      ignore_errors: yes

    - name: Check if ArgoCD installation was successful
      debug:
        msg: "ArgoCD has been successfully installed"
      when: argo_install.rc == 0

    - name: Handle ArgoCD installation failure
      debug:
        msg: "Failed to install ArgoCD. Please check the logs."
      when: argo_install.rc != 0
