---
- name: Install ASDF (version manager)
  hosts: webservers
  become: yes
  tasks:
    - name: Clone ASDF repository
      shell: |
        git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.2
      args:
        creates: ~/.asdf
